identifier: kdy6h8v4rf69pd8a
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /Users/rafaelrochadeazevedo/Code/my-blog
distFolder: dist/my-blog
outDir: /Users/rafaelrochadeazevedo/Code/my-blog/dist/static
handle404: ''
allowErrorCollect: true
